name: Formatting

on:
  push:
    branches:
      - 'staging**'
  pull_request:
    branches:
      '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # formatting and basic install on cpu-only machine
  formatting:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: environment
        run: |
          which python
          python --version

      # temporary install oneccl_bind_pt separately
      - name: Install oneccl_bind_pt
        run: |
          python -m pip install oneccl_bind_pt==2.0 -f https://developer.intel.com/ipex-whl-stable-cpu

      - name: Install deepspeed
        run: |
          pip install .[dev,autotuning]
          ds_report

      - name: Formatting checks
        run: |
           pip show pre-commit clang-format
           pre-commit run --all-files
